language: c

before_install:
  - sudo apt-get install -qq devscripts autoconf automake libtool libldap2-dev libpam0g-dev libdb-dev cdbs libsasl2-dev debhelper libcppunit-dev libkrb5-dev comerr-dev libcap2-dev libexpat1-dev libxml2-dev autotools-dev libltdl-dev
  - ./update_changelog.sh "$VERSION"

script:
  - autoreconf -i
  - debuild -i -us -uc -b

after_success:
  - tar cvzf "$ARTIFACT" ../*.deb
  - git tag "$(echo $VERSION|tr '~' '-')"

branches:
  except:
    - /^[0-9]/

deploy:
  provider: releases
  api-key: "$API_KEY"
  file: "$ARTIFACT"
  skip_cleanup: true

env:
  global:
    - UPSTREAM_VERSION=3.4.6
    - VERSION=$UPSTREAM_VERSION-0~sauce$TRAVIS_BUILD_NUMBER
    - ARTIFACT=/tmp/squid3-$VERSION.tar.gz
    - secure: "WH61+3K+VQ9N6OZEVVJMF0bCadWNi2u5U3JltdjWFNGykhOR+q+KIkQMs5pGE22xLsHrbYieWnovifGIEcOwVuBZAxjGt51alcoKekzRaAiJy0s2qGr2O7WWwErmbFNE4DwksirBnqMPlpxqsuYsv9C/VHZhWCgOiFvRZ1dJ1s0="
    - secure: "IjvbNJkPJaHN5T9DTPuCUKUkaCfWM3fXU3G4KJVmivU0yP6xkedU/P+LrkFcFJXBd9QcCjOJZBzP8fi9/s/QFSfUNABsHsqByWVIa4EoSOFnVuiMA2ZS6A/6NQD7C0tJpARTun7gvWSjix75/3UD7wvST5T2FaEsTT4ZaXHIZvA="
